---
client:
  rate: 20

display:
  enabled: false

world:
  n_random_vehicles: 300
  n_random_walkers: 0

recorder:
  record_truth: true
  format_as: ['avstack']

infrastructure:
  cameras:
    n_spawn: 3
    save: true
  depthcams:
    n_spawn: 3
    save: true
  lidars:
    n_spawn: 3
    save: true
    attributes:
      sensor_tick: 0.1  # faster to capture data

ego:
  idx_spawn: 'randint'
  idx_vehicle: 'lincoln'
  idx_destination: null
  roaming: false
  autopilot: true
  respawn_on_done: false
  max_speed: 30
  sensors:
    - camera 0:
        name: 'CAM_FRONT'
        attributes:
          sensor_tick: 0.10
          fov: 90
          image_size_x: 1600
          image_size_y: 900
        save: true
        noise: {}
        transform:
          location:
            x: 1.6
            y: 0
            z: 1.6
          rotation:
            pitch: 0
            yaw: 0
            roll: 0
    - lidar 0:
        name: 'LIDAR_TOP'
        save: true
        attributes:
          sensor_tick: 0.10
          channels: 32
          rotation_frequency: 20  # needs to be the same as sim rate
          range: 100.0
        noise: {}
        transform:
          location:
            x: -0.5
            y: 0
            z: 1.8
