---
client:
  rate: 20

display:
  # use defaults only

world:
  # use defaults only

recorder:
  # use defaults

infrastructure:
  # use defaults...
  
ego:
  idx_spawn: 1
  idx_vehicle: 0
  max_speed: 20
  sensors:
    - camera 0:
        save: false
    - lidar 0:
        save: false

npc_0:
  type: 'vehicle'
  idx_vehicle: 5
  idx_spawn: 1
  autopilot: true
  delta_spawn:
    x: 10
    y: 0
    z: 0
  events:
    lane_change:
      - [5, 'left']
      - [7, 'right']
    pct_speed:
      - [0, -60]
      - [20, 60]

npc_1:
  type: 'vehicle'
  idx_vehicle: 2
  idx_spawn: 1
  autopilot: true
  delta_spawn:
    x: 16
    y: 0
    z: 0
  events:
    pct_speed:
      - [0, 70]
    lane_change:
      # - [6, 'left']
      - [18, 'right']

npc_2:
  type: 'vehicle'
  idx_vehicle: 2
  idx_spawn: 1
  autopilot: true
  delta_spawn:
    x: 20
    y: 0
    z: 0
  events:
    pct_speed:
      - [0, 70]
    lane_change:
      - [6, 'left']
      # - [18, 'right']

npc_3:
  type: 'vehicle'
  idx_vehicle: 4
  idx_spawn: 1
  autopilot: true
  delta_spawn:
    x: 0
    y: -3
    z: 0
  events:
    pct_speed:
      - [0, 70]
    lane_change:
      - [6, 'left']
      # - [18, 'right']

npc_4:
  type: 'vehicle'
  idx_vehicle: 7
  idx_spawn: 1
  autopilot: true
  delta_spawn:
    x: 30
    y: -3
    z: 0
  events:
    lane_change:
      - [5, 'left']
      - [7, 'right']
    pct_speed:
      - [0, -60]
      - [20, 60]

npc_5:
  type: 'vehicle'
  idx_vehicle: 3
  idx_spawn: 1
  autopilot: true
  delta_spawn:
    x: 60
    y: 0
    z: 0
