---
client:
  rate: 20

display:
  # use defaults only

world:
  # use defaults only

recorder:
  # use defaults

infrastructure:
  # use defaults...

ego:
  idx_spawn: 6
  idx_vehicle: 0
  idx_destination: null
  delta_destination:
    forward: 30
    right: 0
    up: 0
  roaming: false
  respawn_on_done: true
  max_speed: 20  # m/s
  sensors:
    - camera 0:
        save: false
    - lidar 0:
        save: false
    - gnss 0:
        save: false

# npc_0:
#   type: 'vehicle'
#   idx_vehicle: 0
#   idx_spawn: 6
#   autopilot: true
#   delta_spawn:
#     x: 0
#     y: 20
#     z: 0
#   events:
#     pct_speed:
#       - [0, -60]
#       - [20, 60]

# npc_1:
#   type: 'vehicle'
#   idx_vehicle: 0
#   idx_spawn: 6
#   autopilot: true
#   delta_spawn:
#     x: 10
#     y: 50
#     z: 0
#   events:
#     pct_speed:
#       - [0, 70]
#     # lane_change:
#       # - [6, 'left']
#       # - [18, 'right']
